### ISSUE TITLE
Add "*Solution.*" boilerplate to `.sol`?

### ISSUE THREAD

**Issue by d-morrison** [coatless-quarto/assign#3]
Thanks for this fantastic extension! I'm writing to ask if there's an easy way to add an initial line with "*Solution.*" or similar to the `.sol` div class? So the output of the template with the `solution` profile would be:

<img width="569" alt="image" src="https://github.com/user-attachments/assets/9d218f7f-da53-4049-9bed-4370fc4f7e0c">

Glad to make my own PR and/or fork for this! Just not sure what to edit (I haven't learned lua yet).

**Comment by coatless** [comment]
Done in #4, please obtain a new copy of the extension by typing in Terminal:

```sh
quarto add coatless-quarto/assign
```

<img width="812" alt="Screenshot with prefixed solution." src="https://github.com/user-attachments/assets/c159ab56-49a9-4a02-8e71-495663c92021">

**Comment by d-morrison** [comment]
Thanks!! Works great.
